### ISSUE TITLE
Installation issue.

### ISSUE THREAD

**Issue by SirBenjys** [sidneypepo/rtl88x2bu_linux_setup#1]
Linux newbie here, I was attempting to install this when I got these errors:

```
_****[*]` Building driver... /make: *** No targets specified and no makefile found.  Stop.
DONE!**
[*] Installing driver... /make: *** No rule to make target 'install'.  Stop.
DONE!**_

[i] Press [ENTER] to activate your RTL88x2BU. NOTE: Your network connection will be restarted and this can take some seconds!

modprobe: FATAL: Module 88x2bu not found in directory /lib/modules/5.8.0-7642-generic
[i] Setup completed successfully! Press [ENTER] exit setup.

```
![IMG_20210211_192625](https://user-images.githubusercontent.com/78770434/107821535-a947e200-6d4a-11eb-87d9-2f6286bf9582.jpg)

Any help would be appreciated-- this driver setup has gotten me further than anything else I've tried! 

Thank you.

**Comment by sidneypepo** [comment]
Hello o/
First of all, thank you so much for report this issue!
I just updated the script a few minutes ago. Please test the new version and tell me if this issue persists.

**Comment by SirBenjys** [comment]
Thank you so much!
The install is now completely seamless-- no issues whatsoever!
